RestoTuto/RestoTuto/Models/Resto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestoTuto.Models
{
    public class Resto
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Telephone { get; set; }
    }
}

RestoTuto/RestoTuto/Models/RestoList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestoTuto.Models
{
    public class RestoList
    {
        private List<Resto> Restos;
        public List<SelectListItem> RestosNames;
        public Resto Resto;
        public SelectListItem RestoName;

        public RestoList()
        {
            RestosNames = new List<SelectListItem>();
            Restos = new List<Resto>();
            RestoName = new SelectListItem();

            Restos.Add(new Resto { Id = 0, Nom = "RestoUn", Telephone = "0101010101" });
            Restos.Add(new Resto { Id = 1, Nom = "RestoDeux", Telephone = "0202020202" });
            Restos.Add(new Resto { Id = 2, Nom = "RestoTrois", Telephone = "0303030303" });
            Restos.Add(new Resto { Id = 3, Nom = "RestoQuatre", Telephone = "0404040404" });
            Restos.Add(new Resto { Id = 4, Nom = "RestoCinq", Telephone = "0505050505" });
            
            foreach (var elem in Restos)
            {
                RestosNames.Add(new SelectListItem { Text = elem.Nom, Value = RestosNames.Count.ToString() });
            }
        }

        public List<Resto> ObtientTousLesRestaurants()
        {
            return Restos;
        }

        public List<Resto> CreerUnRestaurant(List<Resto> restos, string nom, string telephone)
        {
            restos.Add(new Resto { Id = restos.Count, Nom = nom, Telephone = telephone });
            return restos;
        }

        public void AjouterUnRestaurant(string nom, string telephone)
        {
            Restos.Add(new Resto { Id = Restos.Count, Nom = nom, Telephone = telephone });
        }

        public void ModifierRestaurant(int id, string nom, string telephone)
        {
            Resto restoTrouve = Restos.FirstOrDefault(resto => resto.Id == id);
            if (restoTrouve != null)
            {
                restoTrouve.Nom = nom;
                restoTrouve.Telephone = telephone;
            }
        }

        public List<Resto> ChangerRestaurant(List<Resto> restos, int id, string nom, string telephone)
        {
            Resto restoTrouve = restos.FirstOrDefault(resto => resto.Id == id);
            if (restoTrouve != null)
            {
                restoTrouve.Nom = nom;
                restoTrouve.Telephone = telephone;
            }
            return restos;
        }

        public Resto GetRestoById(int id)
        {
            Resto restoTrouve = Restos.FirstOrDefault(resto => resto.Id == id);
            return restoTrouve;
        }
    }
}

RestoTuto/RestoTuto/Models/Sondage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestoTuto.Models
{
    public class Sondage
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public virtual List<Vote> Votes { get; set; }
    }
}

RestoTuto/RestoTuto/Models/Utilisateur.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestoTuto.Models
{
    public class Utilisateur
    {
        public int Id { get; set; }
        public string Prenom { get; set; }
    }
}

RestoTuto/RestoTuto/Models/Vote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestoTuto.Models
{
    public class Vote
    {
        public int Id { get; set; }
        public virtual Resto Resto { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}

RestoTuto/RestoTuto/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestoTuto.ViewModels
{
    public class HomeViewModel
    {
        public string Message { get; set; }
        public DateTime Date { get; set; }
        public Models.Resto Resto { get; set; }
    }
}

RestoTuto/RestoTuto/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestoTuto.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

RestoTuto/RestoTuto/Controllers/HomeController.cs
using RestoTuto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestoTuto.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            RestoList r = new RestoList();
            return View(r);
        }

        public ActionResult CreateResto()
        {
            RestoList r = new RestoList();
            return PartialView("CreateResto", r);
        }

        [HttpPost]
        public ActionResult UpdateRestos(RestoList r)
        {
            Console.WriteLine("Check");
//            System.Diagnostics.Debug.WriteLine(r.Resto.Nom);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int restoId)
        {
            RestoList r = new RestoList();
            Resto resto = r.GetRestoById(restoId);
            return PartialView("Details", resto);
        }
    }
}

RestoTuto/RestoTuto/Controllers/MessagerieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestoTuto.Controllers
{
    public class MessagerieController : Controller
    {
        // GET: Messagerie
        public ActionResult Index()
        {
            return View();
        }
    }
}

RestoTuto/RestoTuto/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestoTuto.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

RestoTuto/RestoTuto/Views/Contact/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

RestoTuto/RestoTuto/Views/Home/CreateResto.cshtml
@model RestoTuto.Models.RestoList


    <div class="modal-body" id="myModal" style="background-color:snow">
        @using (Html.BeginForm("UpdateRestos", "Home", FormMethod.Post, new {id = "AddResto", enctype = "multipart/form-data" }))
        {
        <fieldset>
            <legend>Restaurant</legend>


            @Html.TextBoxFor(model => model.Resto.Id, new { @hidden = "hidden" })

            <div class="row" style="margin-bottom: 5px">
                <label class="col-sm-4">
                    @Html.LabelFor(model => model.Resto.Nom)
                </label>
                <div class="col-sm-4">
                    @Html.EditorFor(model => model.Resto.Nom)
                </div>
            </div>
            <div class="row" style="margin-bottom: 5px">
                <label class="col-sm-4">
                    @Html.LabelFor(model => model.Resto.Telephone)
                </label>
                <div class="col-sm-4">
                    @Html.EditorFor(model => model.Resto.Telephone)
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success" style="width:135px;">Ajouter</button>
                </div>
            </div>

        </fieldset>
        }

    </div>

RestoTuto/RestoTuto/Views/Home/Details.cshtml
@model RestoTuto.Models.Resto

<div class="row" style="margin-bottom: 5px">
    <label class="col-sm-4">
        @Html.LabelFor(model => model.Nom)
    </label>
    <div class="col-sm-4">
        @Html.DisplayFor(model => model.Nom)
    </div>
</div>
<div class="row" style="margin-bottom: 5px">
    <label class="col-sm-4">
        @Html.LabelFor(model => model.Telephone)
    </label>
    <div class="col-sm-4">
        @Html.DisplayFor(model => model.Telephone)
    </div>
</div>

RestoTuto/RestoTuto/Views/Home/Index.cshtml
@model RestoTuto.Models.RestoList
@{
    WebGrid webGrid = new WebGrid(source: Model.ObtientTousLesRestaurants(), rowsPerPage: 100);
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        Je suis la vue Index
    </div>
    <br />
    <br />
    <button class="btn btn-primary" style="col-sm-1" onclick="location.href='@Url.Action("CreateResto", "Home")'">Ajouter</button>
    <input type="submit" data-toggle="modal" data-target="#myModal" value="Search" />
    <a href="javascript:void(0);" class="addData">Add</a>
    <input type="button" id="btnAdd" value="AddResto" />

    <div id='myModal' class='modal'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent'></div>
            </div>
        </div>

    </div>

    <div>
        @{
            Html.RenderPartial("CreateResto");
        }
    </div>
    <div class="row">
        <div style="float: left">
            <a href=" @Url.Action("Index" , "Messagerie")"><img src="~/Images/bouton-message-2.png" class="img-center" height="60" , width="60" /></a>
        </div>

        <div style="float: right">
            <h3>Fréquentation</h3>
            <br />
            <a href=" @Url.Action("Index" , "Home")"><img src="~/Images/bouton-vert.png" class="img-center" height="60" , width="60" /></a>
            <a href=" @Url.Action("Index" , "Home")"><img src="~/Images/bouton-orange.png" class="img-center" height="60" , width="60" /></a>
            <a href=" @Url.Action("Index" , "Home")"><img src="~/Images/bouton-rouge.png" class="img-center" height="60" , width="60" /></a>

        </div>

    </div>
    <div class="row"><br /><br /></div>
    <div class="row">
        <div style="width: auto; float:left">
            @webGrid.GetHtml(
                tableStyle: "webgrid-table",
                headerStyle: "webgrid-header",
                footerStyle: "webgrid-footer",
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-selected-row",
                rowStyle: "webgrid-row-style",
                columns: webGrid.Columns(
                 webGrid.Column("Id"),
                 webGrid.Column("Nom"),
                 webGrid.Column("Telephone"),
                 webGrid.Column("Select", null, format: @<text>@item.GetSelectLink("Select")</text>))
)
        </div>
        <div style="width:auto; height: auto; float:right;">
            <div style="vertical-align:central; ">
                @if (webGrid.HasSelection)
                {
                    int restaurantId = (webGrid.SelectedRow.Value).Id;
                    Html.RenderAction("Details", new { restoId = restaurantId });
                }
            </div>
        </div>
    </div>
        <br />
        <br />
    <div class="row">
        @Html.Label("estMajeur", "Cochez la case si vous êtes majeur")
        @Html.CheckBox("estMajeur", true)
        <input type="submit" value="Envoyer" />
        <br />
        <label for="estMajeur">Cochez la case si vous &#234;tes majeur</label>
        <input checked="checked" id="estMajeur" name="estMajeur" type="checkbox" value="true" /><input name="estMajeur" type="hidden" value="false" />
        <input type="submit" value="Envoyer" />
    </div>
    <br />
    <div>
        @Html.DropDownListFor(model => model.RestoName, Model.RestosNames, new { @class = "form-control" })
    </div>

    <br />
    <br />

    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal2">Open Modal</button>

    <!-- Modal -->
    <div id="myModal2" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body" id="myModal2" style="background-color:snow">
                    @using (Html.BeginForm("UpdateRestos", "Home"))
                    {
                    <fieldset>
                        <legend>Restaurant</legend>


                        @Html.TextBoxFor(model => model.Resto.Id, new { @hidden = "hidden" })

                        <div class="row" style="margin-bottom: 5px">
                            <label class="col-sm-4">
                                @Html.LabelFor(model => model.Resto.Nom)
                            </label>
                            <div class="col-sm-4">
                                @Html.EditorFor(model => model.Resto.Nom)
                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 5px">
                            <label class="col-sm-4">
                                @Html.LabelFor(model => model.Resto.Telephone)
                            </label>
                            <div class="col-sm-4">
                                @Html.EditorFor(model => model.Resto.Telephone)
                            </div>
                        </div>
                        <div class="row">
                            <input type="submit" value="send data" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                        </div>

                    </fieldset>
                    }

                </div>


            </div>

        </div>
    </div>
</body>
</html>

RestoTuto/RestoTuto/Views/Home/RestoWebGrid.cshtml
@model RestoTuto.Models.RestoList

@{ 
        WebGrid webGrid = new WebGrid(source: Model.ObtientTousLesRestaurants(), rowsPerPage: 100);
}

RestoTuto/RestoTuto/Views/Messagerie/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        page messagerie
    </div>
</body>
</html>

RestoTuto/RestoTuto/Views/Shared/WebGrid.cshtml
<style type="text/css">
    .Grid-table
    {
        font-family: "Trebuchet MS" , Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #98BF21;
        background-color: white;
    }
    .Grid-table td, th
    {
        border: 1px solid #98BF21;
        padding: 3px 7px 2px;
    }
    .Grid-header
    {
        background-color: #A7C942;
        color: #FFFFFF;
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: left;
    }
    .Grid-footer
    {
    }
    .Grid-row-style
    {
        padding: 3px 7px 2px;
    }
    .Grid-alternating-row
    {
        background-color: #EAF2D3;
        padding: 3px 7px 2px;
    }
</style>

RestoTuto/RestoTuto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yorder</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=" @Url.Action("Index" , "Home")"><img src="~/Images/YORDER1.png" class="img-center" height="60" , width="60" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                    <li>@Html.ActionLink("Menu", "Index", "Profile")</li>
                    <li>@Html.ActionLink("Reservation", "Index", "Profile")</li>
                    <!--<li>@Html.ActionLink("Yorder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>-->
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <style type="text/css">
        a.navbar-brand {
            background: url('@Url.Content("~/Images/YORDER1.png")');
        }

        .navbar-inverse {
            background-color: #7c0724 !important;

        }

        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }

        .webgrid-header {
            background-color: #A7C942;
            color: #FFFFFF;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: left;
        }

        .webgrid-footer {
        }

        .webgrid-row-style {
            padding: 3px 7px 2px;
        }

        .webgrid-alternating-row {
            background-color: #EAF2D3;
            padding: 3px 7px 2px;
        }
    </style>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script>
        $(document).ready(function () {

            $('AddResto').submit(function (e) {
                e.preventDefault();
                var $form = $(this);

                $.post($form.attr("action"), $form.serialize()).done(function (res) {
                    $mymodal = $("#myModal");
                    //update the modal's body with the response received
                    $mymodal.find("div.modal-body").html(res);
                    // Show the modal
                    $mymodal.modal("show");
                });
            });

        });
    </script>

    <script>
        var TeamDetailPostBackURL = '/Home/CreateResto';
        $(function () {
            $(".addData").click(function () {
                debugger;
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "POST",
                    url: TeamDetailPostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            //$("#closebtn").on('click',function(){
            //    $('#myModal').modal('hide');

            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
        });

    </script>

    <script>
        $("body").on("click", "#btnAdd", function () {
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            debugger;
            $.ajax({
                type: "POST",
                url: "/Home/CreateResto",
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContent').html(data);
                    $('#myModal').modal(options);
                    $('#myModal').modal('show');

                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });

        });

    </script>

    <script>
        function ShowMessage() {
            var result = confirm("Voulez-vous changez la frequentation du restaurant ? ");
            if (result) {
                return true;
            } else {
                return false;
            }
        }
    </script>

</body>
</html>